//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Payment
    {
        public int Invoice_No { get; set; }
        public Nullable<bool> Pay_Status { get; set; }
        public Nullable<double> Bill { get; set; }
        public string Payment_Mode { get; set; }
        public Nullable<System.DateTime> Payment_time { get; set; }
        public Nullable<int> Order_ID { get; set; }
    
        public virtual Order_Details Order_Details { get; set; }
    }
}
